# Generated by Django 4.2.26 on 2025-11-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('current_stage', models.CharField(choices=[('lead', 'Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('docs_pending', 'Docs Pending'), ('docs_received', 'Docs Received'), ('application_started', 'Application Started'), ('application_submitted', 'Application Submitted'), ('application_in_process', 'Application In Process'), ('application_approved', 'Application Approved'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('lost', 'Lost'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='lead', max_length=50)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('from_stage', models.CharField(blank=True, max_length=50)),
                ('to_stage', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(help_text='User who made this stage change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='client.client')),
            ],
            options={
                'verbose_name': 'client stage history',
                'verbose_name_plural': 'client stage histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('chat_session_id', models.UUIDField(blank=True, db_index=True, help_text='Link to chat session if lead came from chatbot', null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Flexible JSON field to store any context information')),
                ('client', models.OneToOneField(help_text='Client this context belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='context', to='client.client')),
            ],
            options={
                'verbose_name': 'client context',
                'verbose_name_plural': 'client contexts',
                'db_table': 'client_context',
            },
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(help_text='User who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='Customer Support user assigned to this client', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='client.client')),
            ],
            options={
                'verbose_name': 'client assignment',
                'verbose_name_plural': 'client assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'phone'], name='client_clie_email_14bf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['current_stage', '-created_at'], name='client_clie_current_ff484d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientstagehistory',
            index=models.Index(fields=['client', '-created_at'], name='client_clie_client__a22ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontext',
            index=models.Index(fields=['client'], name='client_cont_client__634749_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontext',
            index=models.Index(fields=['chat_session_id'], name='client_cont_chat_se_de83ba_idx'),
        ),
        migrations.AddIndex(
            model_name='clientassignment',
            index=models.Index(fields=['assigned_to', 'is_active'], name='client_clie_assigne_6dd145_idx'),
        ),
        migrations.AddIndex(
            model_name='clientassignment',
            index=models.Index(fields=['client', 'is_active'], name='client_clie_client__085b6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client',), name='unique_active_assignment'),
        ),
    ]
