# Generated by Django 4.2.26 on 2025-11-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientContext',
        ),
    ]
