# Generated by Django 4.2.26 on 2025-11-26 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_alter_client_email_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstagehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made this stage change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientstagehistory',
            name='from_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
