# Generated by Django 4.2.26 on 2025-11-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientstagehistory_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='AI-summarized context from chat history (intent, preferences, etc.)'),
        ),
    ]
