# Generated by Django 4.2.26 on 2025-11-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_clients', 'Can view all clients'), ('assign_client', 'Can assign clients to users'), ('change_client_stage', 'Can change client stage')], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
