# Generated by Django 4.2.26 on 2025-11-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True)),
                ('message', models.TextField()),
                ('sender_type', models.CharField(choices=[('bot', 'Bot'), ('client', 'Client')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chat history',
                'verbose_name_plural': 'chat histories',
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['session_id', 'sent_at'], name='chat_chathi_session_2ef331_idx')],
            },
        ),
    ]
