# Generated by Django 4.2.26 on 2025-11-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_delete_clientcontext'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='data_type',
            field=models.CharField(choices=[('message', 'Regular Message'), ('name', 'Name'), ('email', 'Email'), ('phone', 'Phone Number')], default='message', help_text='Type of data being sent (for client info collection)', max_length=20),
        ),
    ]
